### ISSUE TITLE
5.1 - CRIAÇÃO DO BANCO DE DADOS DE ALERTA

### ISSUE THREAD

**Issue by gustavols** [Conveccao/conveccao-backend#32]
# CRIAÇÃO DO BANCO DE DADOS DE ALERTA

## **Definition of Ready:**

**Descrição:** Realizar a criação do banco de dados de alerta contendo os seguintes campos:

TIPO DE OCORRENCIA, LOCAL, DATA E HORA

ex:
TIPO DE OCORRENCIA: POSSIVEL RISCO DE DESLIZAMENTO DE CHUVA
LOCAL: ESTAÇÃO CAMPOS DO JORDÃO
DATA: 13/12/2022
HORA: 13:29:00

BANCO INDICADO: POSTGREESQL.

**PRIORIDADE DO ITEM:** ALTA.

**USER STORY:** 11.

**PESO:** 5.

**REQUISITO:** FUNCIONAL.

## **Definition of Done:** 

**CHECKLIST DE ITENS :**

- [ ] BANCO DE DADOS TEM QUE ESTAR COM TODOS OS CAMPOS SOLICITADOS ACIMA E CONFIGURADO PARA RECIMENTO E CADASTRO DE DADOS.

**Comment by annakks** [comment]
inicio e termino dia 17/11/2022 duração 1 hora
