### ISSUE TITLE
13.1	CRIAÇÃO DO SWAGGER (BACK)

### ISSUE THREAD

**Issue by bruno-pisciotta281** [Conveccao/conveccao-backend#6]
Criação da documentação da sprint no software swagger.

**Peso:** 5

**Prioridade:** BAIXA

**Data de Inicio:** 30/08/2022 - 07;30

**DoD**

**[  ]** Documento criado e configurado para uso

**Comment by Nathtruyts** [comment]
Os códigos já estão prontos, o que falta é descrever todas a rotas atuais no json.
